version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    # Volumes para desenvolvimento (opcional)
    # volumes:
    #   - ./dist:/usr/share/nginx/html
    #   - ./nginx.conf:/etc/nginx/conf.d/default.conf 